name: Slog CI Testing
on:
  push:
    branches: [ master, github-actions-test]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker build -t slog-ci-test .

      - name: Compiler tests
        run: docker run --rm --entrypoint racket slog-ci-test /slog/compiler/unit-tests/tests.rkt -c --run-slow-tests

      - name: Compiler tests with --merge-builtins
        run: docker run --rm --entrypoint racket slog-ci-test /slog/compiler/unit-tests/tests.rkt -c --merge-builtins --run-slow-tests

      - name: C++ compilation tests
        run: docker run --rm --entrypoint bash slog-ci-test /slog/compiler/unit-tests/cpp_compilation_tests.sh

      - name: Compile hashes
        run: docker run --rm --entrypoint bash slog-ci-test /slog/slog/tests/run_test.sh compile_hashes

      # TODO: Backend tests (Yihao working on them)

    # TODO: integrate benchmarking into CI,
    #       maybe into some persistent store so we can track perf over time?
    # - name: benchmark-worstcase-4-terms-2-m
    #   working-directory: ./compiler
    #   run: |
    #     START=$(date +%s)
    #     echo quit | racket slog.rkt -i ./ci-benchmarks/worstcase-4-terms-2-m.slog
    #     END=$(date +%s)
    #     DIFF=$(echo "$END - $START" | bc)
    #     echo "took $DIFF seconds."
    #     if [ $DIFF -gt  300 ]
    #     then
    #       echo took too long
    #       exit 1
    #     fi
